<?php
/**
 *
 *
 * @author  Masamoto Miyata <miyata@able.ocn.ne.jp>
 * @create  2011/12/21
 * @version  v 1.0 2011/12/21 15:45 Miyata
 **/
class Bd_Acl_Admin implements Sdx_Acl_Directory
{
	public function isAllowed(Sdx_Context $context)
	{
		//TODO Please implement this method.
		throw new Sdx_Exception('This method is generated by enable-acl script. Please implement this method.');
	}
}