<?php

require_once 'Bd/Db/Record.php';
require_once 'Bd/Orm/Main/Table/AutoLogin.php';
require_once 'Bd/Orm/Main/Const/AutoLogin.php';

abstract class Bd_Orm_Main_Base_AutoLogin extends Bd_Db_Record
{

    private static $_table_class = null;

    /**
     * @return Bd_Orm_Main_Table_AutoLogin
     */
    public static function getTable()
    {
        if(!self::$_table_class)
        {
            self::$_table_class = new Bd_Orm_Main_Table_AutoLogin();
            self::$_table_class->lock();
        }
        
        
        return self::$_table_class;
    }

    /**
     * @return Bd_Orm_Main_Table_AutoLogin
     */
    protected function _getTable()
    {
        return self::getTable();
    }

    /**
     * @return Bd_Orm_Main_Table_AutoLogin
     */
    public static function createTable()
    {
        return new Bd_Orm_Main_Table_AutoLogin();
    }

    /**
     * @return Bd_Orm_Main_Form_AutoLogin
     */
    public static function createForm(array $except = array())
    {
        return new Bd_Orm_Main_Form_AutoLogin('', array(), $except);
    }

    public function getHash()
    {
        return $this->_get('hash');
    }

    /**
     * @return Bd_Orm_Main_AutoLogin
     */
    public function setHash($value)
    {
        return $this->_set('hash', $value);
    }

    public function getAccountId()
    {
        return $this->_get('account_id');
    }

    /**
     * @return Bd_Orm_Main_AutoLogin
     */
    public function setAccountId($value)
    {
        if(isset($this->_relations['Account']) && $value != $this->getAccountId())
        {
            unset($this->_relations['Account']);
        }
        
        return $this->_set('account_id', $value);
    }

    public function getExpireDate()
    {
        return $this->_get('expire_date');
    }

    /**
     * @return Bd_Orm_Main_AutoLogin
     */
    public function setExpireDate($value)
    {
        return $this->_set('expire_date', $value);
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyOne
     *
     * @return Bd_Orm_Main_Account
     */
    public function getAccount($arg = null)
    {
        $this->_relation_save = true;
        
        if($arg || !array_key_exists('Account', $this->_relations))
        {
        	$account_id = $this->getAccountId();
        	
        	if($account_id)
        	{
        	   list($select, $db) = $this->_detectGetterArg($arg, 'getAccountSelect');
        		
        	    $table = Bd_Orm_Main_Account::getTable();
        		$select->add('id', $account_id);
        		$record = $table->fetchRow($select);
        	}
        	else
        	{
        		$record = null;
        	}
        	
        	$this->_relations['Account'] = $record;
        }
        
        return $this->_relations['Account'] === null ? Sdx_Null::getInstance() : $this->_relations['Account'];
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyOne
     *
     * @return Bd_Orm_Main_AutoLogin
     */
    public function setAccount(Bd_Orm_Main_Account $record)
    {
        $this->_relation_save = true;
        $record->poolAutoLogin($this);
        
        $this->setAccountId($record->getId());
        
        $this->_relations['Account'] = $record;
        return $this;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyOne
     *
     * @return Bd_Orm_Main_AutoLogin
     */
    public function bindAccount(Bd_Orm_Main_Account $record = null, $oposite = false)
    {
        $this->_relation_save = true;
        $this->_relations['Account'] = $record;
        
        if($record && $oposite)
        {
        	$record->bindAutoLogin($this);
        }
        
        
        return $this;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyOne
     *
     * @return Sdx_Db_Select
     */
    public function getAccountSelect(Sdx_Db_Adapter $db = null)
    {
        return Bd_Orm_Main_Account::getTable()->getSelect($db);
    }


}

