<?php

require_once 'Bd/Db/Record.php';
require_once 'Bd/Orm/Main/Table/Tag.php';
require_once 'Bd/Orm/Main/Const/Tag.php';

abstract class Bd_Orm_Main_Base_Tag extends Bd_Db_Record
{

    private static $_table_class = null;

    /**
     * @return Bd_Orm_Main_Table_Tag
     */
    public static function getTable()
    {
        if(!self::$_table_class)
        {
            self::$_table_class = new Bd_Orm_Main_Table_Tag();
            self::$_table_class->lock();
        }
        
        
        return self::$_table_class;
    }

    /**
     * @return Bd_Orm_Main_Table_Tag
     */
    protected function _getTable()
    {
        return self::getTable();
    }

    /**
     * @return Bd_Orm_Main_Table_Tag
     */
    public static function createTable()
    {
        return new Bd_Orm_Main_Table_Tag();
    }

    /**
     * @return Bd_Orm_Main_Form_Tag
     */
    public static function createForm(array $except = array())
    {
        return new Bd_Orm_Main_Form_Tag('', array(), $except);
    }

    public function getId()
    {
        return $this->_get('id');
    }

    /**
     * @return Bd_Orm_Main_Tag
     */
    public function setId($value)
    {
        return $this->_set('id', $value);
    }

    public function getName()
    {
        return $this->_get('name');
    }

    /**
     * @return Bd_Orm_Main_Tag
     */
    public function setName($value)
    {
        return $this->_set('name', $value);
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyMany
     *
     * @return Bd_Db_Record_List
     */
    public function getThreadList($arg = null)
    {
        $this->_relation_save = true;
        
        if($arg || !array_key_exists('Thread', $this->_relations))
        {
        	if($arg || !array_key_exists('ThreadTag', $this->_relations))
        	{
            	list($select, $db) = $this->_detectGetterArg($arg, 'getThreadSelect');
        	
            	$id = $this->getId();
        
            	if($id)
            	{
            		$table = $select->getTable();
            		$select->add('tag_id', $id, $table->getAlias());
            		$middle_records = $table->fetchAll($select);
            	} else {
            		$middle_records = new Bd_Db_Record_List();
            	}
            
            	$this->_relations['ThreadTag'] = $middle_records;
            	if(isset($this->_tmp_relations['ThreadTag']))
        		{
        			$this->_relations['ThreadTag']->mergeList($this->_tmp_relations['ThreadTag']);
        			$this->_tmp_relations['ThreadTag']->clear();
        		}
        	}
        	
        	$records = new Bd_Db_Record_List();
        	foreach($this->_relations['ThreadTag'] as $middle_record)
            {
        		$middle_record->bindTag($this);
        		$records->mergeRecord($middle_record->getThread());
            }
                    
            $this->_relations['Thread'] = $records;
        	
        }
        
        if(isset($this->_tmp_relations['Thread']))
        {
        	$this->_relations['Thread']->mergeList(
        		$this->_tmp_relations['Thread']
        	);
        	
        	$this->_tmp_relations['Thread']->clear();
        }
                
        return $this->_relations['Thread'];
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyMany
     *
     * @return Bd_Orm_Main_Tag
     */
    public function setThreadList($records)
    {
        $this->_relation_save = true;
        
        $new_mid_records = new Bd_Db_Record_List();
        foreach($records as $key=>$record)
        {
        	$new_mid_record = new Bd_Orm_Main_ThreadTag();
        	$new_mid_record->setTagId($this->getId());
        	$new_mid_record->setThreadId($record->getId());
        	$new_mid_records->mergeRecord($new_mid_record);
        }
        
        if(is_array($records))
        {
        	$records = new Bd_Db_Record_List($records);
        }
        
        $this->_relations['Thread'] = $records;
        $this->_delete_relations['ThreadTag'] = $new_mid_records;
        $this->_relations['ThreadTag'] = $new_mid_records;
        
        if(isset($this->_tmp_relations['Thread']))
        {
        	$this->_tmp_relations['Thread']->clear();
        }
        
        return $this;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyMany
     *
     * @return Bd_Orm_Main_Tag
     */
    public function bindThread(Bd_Orm_Main_Thread $record = null, $oposite = false)
    {
        $this->_relation_save = true;
        
        if(!array_key_exists('Thread', $this->_relations))
        {
        	$this->_relations['Thread'] = new Bd_Db_Record_List();
        }
        
        if($record && !($record instanceof Sdx_Null))
        {
        	$this->_relations['Thread']->mergeRecord($record);
        	
        		if($oposite)
        	{
        		$record->bindTag($this);
        	}
        
        }
        
        return $this;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyMany
     *
     * @return Sdx_Db_Select
     */
    public function getThreadSelect(Sdx_Db_Adapter $db = null)
    {
        $mid_table = Bd_Orm_Main_ThreadTag::createTable();
        $mid_table->addJoinInner(Bd_Orm_Main_Thread::createTable());
        $select = $mid_table->getSelect($db);
        $mid_table->appendJoin($select);
        
        return $select;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyMany
     *
     * @return Bd_Orm_Main_Tag
     */
    public function addThread(Bd_Orm_Main_Thread $record)
    {
        $this->_relation_save = true;
        
        $new_mid_record = new Bd_Orm_Main_ThreadTag();
        $new_mid_record->setTagId($this->getId());
        $new_mid_record->setThreadId($record->getId());
        
        $this->addThreadTag($new_mid_record);
        $record->addThreadTag($new_mid_record);
        
        if(!isset($this->_tmp_relations['Thread']))
        {
        	$this->_tmp_relations['Thread'] = new Bd_Db_Record_List();
        }
        $this->_tmp_relations['Thread']->addRecord($record);
        
        return $this;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_ManyMany
     *
     * @return Bd_Orm_Main_Tag
     */
    public function poolThread(Bd_Orm_Main_Thread $record)
    {
        $this->_relation_save = true;
        
        if(!isset($this->_tmp_relations['Thread']))
        {
        	$this->_tmp_relations['Thread'] = new Bd_Db_Record_List();
        }
        
        $this->_tmp_relations['Thread']->addRecord($record);
        return $this;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_OneMany
     *
     * @return Bd_Db_Record_List
     */
    public function getThreadTagList($arg = null)
    {
        $this->_relation_save = true;
        
        if($arg || !array_key_exists('ThreadTag', $this->_relations))
        {
            $id = $this->getId();
        
            if ($id)
            {
                list($select, $db) = $this->_detectGetterArg($arg, 'getThreadTagSelect');
        	
                $table = Bd_Orm_Main_ThreadTag::getTable();
                $select->add('tag_id', $id, 'thread_tag');
                $records = $table->fetchAll($select);
            
                foreach($records as $record)
                {
                    $record->bindTag($this);
                }
            }
            else
            {
                $records = new Bd_Db_Record_List();
            }
                    
            $this->_relations['ThreadTag'] = $records;
        }
        
        if(isset($this->_tmp_relations['ThreadTag']))
        {
        	$this->_relations['ThreadTag']->mergeList(
        		$this->_tmp_relations['ThreadTag']
        	);
        	
        	$this->_tmp_relations['ThreadTag']->clear();
        }
                
        return $this->_relations['ThreadTag'];
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_OneMany
     *
     * @return Bd_Orm_Main_Tag
     */
    public function setThreadTagList($records)
    {
        $this->_relation_save = true;
        
        foreach($records as $key=>$record)
        {
        	$record->setTagId($this->getId());
            $record->bindTag($this);
        }
        
        if(is_array($records))
        {
        	$records = new Bd_Db_Record_List($records);
        }
        
        $this->_exception_relations['ThreadTag'] = $records;
        $this->_relations['ThreadTag'] = $records;
        if(isset($this->_tmp_relations['ThreadTag']))
        {
        	$this->_tmp_relations['ThreadTag']->clear();
        }
        return $this;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_OneMany
     *
     * @return Bd_Orm_Main_Tag
     */
    public function bindThreadTag(Bd_Orm_Main_ThreadTag $record = null, $oposite = false)
    {
        $this->_relation_save = true;
        
        if(!array_key_exists('ThreadTag', $this->_relations))
        {
        	$this->_relations['ThreadTag'] = new Bd_Db_Record_List();
        }
        
        if($record && !($record instanceof Sdx_Null))
        {
        	$this->_relations['ThreadTag']->mergeRecord($record);
        	
        		if($oposite)
        	{
        		$record->bindTag($this);
        	}
        
        }
        
        return $this;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_OneMany
     *
     * @return Sdx_Db_Select
     */
    public function getThreadTagSelect(Sdx_Db_Adapter $db = null)
    {
        return Bd_Orm_Main_ThreadTag::getTable()->getSelect($db);
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_OneMany
     *
     * @return Bd_Orm_Main_Tag
     */
    public function addThreadTag(Bd_Orm_Main_ThreadTag $record)
    {
        $this->_relation_save = true;
        
        $record->bindTag($this);
        $record->setTagId($this->getId());
        
        if(isset($this->_relations['ThreadTag']))
        {
        	$this->_relations['ThreadTag']->mergeRecord($record);
        }
        else
        {
        	if(!isset($this->_tmp_relations['ThreadTag']))
        	{
        		$this->_tmp_relations['ThreadTag'] = new Bd_Db_Record_List();
        	}
        	$this->_tmp_relations['ThreadTag']->addRecord($record);
        }
        
        return $this;
    }

    /**
     * Generated by Sdx_Generator_Model_Relation_OneMany
     *
     * @return Bd_Orm_Main_Tag
     */
    public function poolThreadTag(Bd_Orm_Main_ThreadTag $record)
    {
        $this->_relation_save = true;
        
        if(!isset($this->_tmp_relations['ThreadTag']))
        {
        	$this->_tmp_relations['ThreadTag'] = new Bd_Db_Record_List();
        }
        
        $this->_tmp_relations['ThreadTag']->addRecord($record);
        return $this;
    }


}

