routes:
#  sample:
#    route:          /:placeholder/:controller/:action
#    defaults:
#      module:       default
#      controller:   index
#      action:       index
#    reqs:
#      placeholder:     '[a-z]{2}'

#  regex_sample:
#    type:         Zend_Controller_Router_Route_Regex
#    route:        job-(\d+)/([^/]+)
#    defaults:
#      module:     default
#      controller: job
#    map:
#      1:          job_id
#      2:          action