routes:
#  sample:
#    route:          /:placeholder/:controller/:action
#    defaults:
#      module:       default
#      controller:   index
#      action:       index
#    reqs:
#      placeholder:     '[a-z]{2}'

#  regex_sample:
#    type:         Zend_Controller_Router_Route_Regex
#    route:        job-(\d+)/([^/]+)
#    defaults:
#      module:     default
#      controller: job
#    map:
#      1:          job_id
#      2:          action

  thread_default:
    route:         /thread/:thread_id/:action
    defaults:
      module:      default
      controller:  thread
      action:      index
    reqs:
      thread_id:   '[0-9]+'

  account_default:
    route:         /account/:action
    defaults:
      module:      default
      controller:  account
      action:      index

  control_default:
    route:         /control/:action
    defaults:
      module:      default
      controller:  control
      action:      index